name: verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: 11

    - name: Install npm modules
      run:
        yarn install

    - name: Verify app
      run:
        yarn lint

    - name: Build app
      run:
        yarn generate
